name: Demo Verification

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test setup script
      run: |
        python test_setup.py
      env:
        # This will fail the API test, but other tests should pass
        GEMINI_API_KEY: "test-key-not-real"
    
    - name: Verify project structure
      run: |
        test -f README.md
        test -f app.py
        test -f requirements.txt
        test -d data
        test -d demo
        echo "✅ Project structure verified"
